services:
  - type: web
    name: organizational-management-sys
    env: node
    rootDir: .
    buildCommand: |
      npm install
      cd frontend && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: organizational-db
          property: connectionString
    plan: free
    region: singapore
